export const MOCK_MIGRATION = [
  {
    "headFamilyFirstName": "ALEIDA AZUCENA GALINDO PARRA",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 20928312,
    "headFamilyPhone": 3224403161,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "ALEIDA AZUCENA GALINDO PARRA",
    "cedula": 20928312,
    "telefono": 3224403161,
    "email": "",
    "finca": "LA ESPERANZA PARCELA 19 A",
    "latitud": 4.47224,
    "longitud": -74.33828,
    "registroCatastral": "157-102235",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "A1 -A5: Pobreza extrema",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 700000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "ANGELICA MARIA ALARCON RODRIGUEZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 1069721288,
    "headFamilyPhone": 3123753632,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "ANGELICA MARIA ALARCON RODRIGUEZ",
    "cedula": 1069721288,
    "telefono": 3123753632,
    "email": "maria.angelica.akaix@gmail.com",
    "finca": "LOTE # 4",
    "latitud": 4.46208,
    "longitud": -74.325981,
    "registroCatastral": "157-106044",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Desplazada",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "4. Poseedor",
    "gastosUltimoMes": 500000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "BERTHA CECILIA MUÑOZ DE VILLABAL",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 20822788,
    "headFamilyPhone": 3105818810,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "BERTHA CECILIA MUÑOZ DE VILLABAL",
    "cedula": 20822788,
    "telefono": 3105818810,
    "email": "",
    "finca": "PAREDA 23",
    "latitud": "",
    "longitud": "",
    "registroCatastral": "157-48612",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 3,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Adulto mayor",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "BLANCA EDID PACHON NIETO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 23801051,
    "headFamilyPhone": 3213056588,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "BLANCA EDID PACHON NIETO",
    "cedula": 23801051,
    "telefono": 3213056588,
    "email": "edithpachon08@gmail.com",
    "finca": "EL RECUERDO",
    "latitud": 4.46778,
    "longitud": -74.31873,
    "registroCatastral": "157-132",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 700000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "CECILIA UBAQUE MORENO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 20927525,
    "headFamilyPhone": 3124895902,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "CECILIA UBAQUE MORENO",
    "cedula": 20927525,
    "telefono": 3124895902,
    "email": "ceciliaubaquemoreno@hotmail.com",
    "finca": "PARCELA 13",
    "latitud": 4.42646,
    "longitud": -74.33062,
    "registroCatastral": "157-51242",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 500000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "DINA LUZ RAMIREZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 35252221,
    "headFamilyPhone": 3118761860,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "DINA LUZ RAMIREZ",
    "cedula": 35252221,
    "telefono": 3118761860,
    "email": "dinaluzramirez4@hotmail.com",
    "finca": "EL PROGRESO",
    "latitud": 4.46571,
    "longitud": -74.33853,
    "registroCatastral": "157-83160",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "2. Arrendatario",
    "gastosUltimoMes": 500000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "DORA ALCIRA NOVOA PRIETO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 35251006,
    "headFamilyPhone": 3204623935,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "DORA ALCIRA NOVOA PRIETO",
    "cedula": 35251006,
    "telefono": 3204623935,
    "email": "",
    "finca": "PARCELA 7 LOTE 5",
    "latitud": 4.45805,
    "longitud": -74.31993,
    "registroCatastral": "157-109299",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 1,
    "grupoEtnico": "Madre cabeza familia",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "4. Poseedor",
    "gastosUltimoMes": 700000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "ELVIA MARINA RODRIGUEZ MONTAÑO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 39616691,
    "headFamilyPhone": 3132661298,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "ELVIA MARINA RODRIGUEZ MONTAÑO",
    "cedula": 39616691,
    "telefono": 3132661298,
    "email": "mr9875174@gmail.com",
    "finca": "CANOAS",
    "latitud": 4.4585,
    "longitud": -74.3192,
    "registroCatastral": "157-109298",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 6,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Adulto mayor",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "DI-D21: Población no pobre",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 550000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "FLOR ALBA AMAYA UBAQUE",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 39618960,
    "headFamilyPhone": 3192858534,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "FLOR ALBA AMAYA UBAQUE",
    "cedula": 39618960,
    "telefono": 3192858534,
    "email": "floramaya0502@gmail.com",
    "finca": "EL ALJIBE",
    "latitud": 4.46379,
    "longitud": -74.32283,
    "registroCatastral": "157-95158",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 2,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 150000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "GERARDO URIEL SOLORZANO RODRIGUEZ",
    "headFamilyGender": "Hombre",
    "headFamilyIdentification": 11258363,
    "headFamilyPhone": 3102391957,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "GERARDO URIEL SOLORZANO RODRIGUEZ",
    "cedula": 11258363,
    "telefono": 3102391957,
    "email": "",
    "finca": "el arenal",
    "latitud": "",
    "longitud": "",
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 4,
    "grupoEtnico": "Campesino",
    "lugarResidencia": "finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "DI-D21: Población no pobre",
    "accesoTierra": "si",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "si",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "GERARDO VARGAS SALAMANCA",
    "headFamilyGender": "Hombre",
    "headFamilyIdentification": 3171717,
    "headFamilyPhone": 3228414423,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "GERARDO VARGAS SALAMANCA",
    "cedula": 3171717,
    "telefono": 3228414423,
    "email": "",
    "finca": "el arenal",
    "latitud": 4.27679,
    "longitud": -74.18922,
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 1,
    "miembrosHogarEconomicamenteResponsables": 1,
    "grupoEtnico": "Discapacitado",
    "lugarResidencia": "finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "si",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "si",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "GLADYS ALCIRA FORERO DE BABATIVA",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 39612372,
    "headFamilyPhone": 3158342838,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "GLADYS ALCIRA FORERO DE BABATIVA",
    "cedula": 39612372,
    "telefono": 3158342838,
    "email": "",
    "finca": "PARCELA 17",
    "latitud": 4.45699,
    "longitud": -74.32441,
    "registroCatastral": "157-31727",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 2,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Discapacitado",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 450000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "GLORIA MAGALI GALINDO SERRATO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 1075598466,
    "headFamilyPhone": 3003366734,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "GLORIA MAGALI GALINDO SERRATO",
    "cedula": 1075598466,
    "telefono": 3003366734,
    "email": "",
    "finca": "la ladera",
    "latitud": 4.27037,
    "longitud": -74.2017,
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 3,
    "miembrosHogarEconomicamenteResponsables": 3,
    "grupoEtnico": "Madre cabeza familia",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "A1 -A5: Pobreza extrema",
    "accesoTierra": "no",
    "relacionTenenciaTierra": "2. Arrendatario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "si",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "HEIDY YASMIN RODRIGUEZ GALINDO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 53100325,
    "headFamilyPhone": 3224717809,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "HEIDY YASMIN RODRIGUEZ GALINDO",
    "cedula": 53100325,
    "telefono": 3224717809,
    "email": "heidyrodriguezg0211@gmail.com",
    "finca": "LOTE 7 PARCELACIÓN SANTA MARTA",
    "latitud": 4.44116,
    "longitud": -74.35085,
    "registroCatastral": "157-123333",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 5,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "4. Poseedor",
    "gastosUltimoMes": 800000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "HELIODORO GALINDO PARRA",
    "headFamilyGender": "Hombre",
    "headFamilyIdentification": 3172027,
    "headFamilyPhone": 3144271588,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "HELIODORO GALINDO PARRA",
    "cedula": 3172027,
    "telefono": 3144271588,
    "email": "",
    "finca": "",
    "latitud": "",
    "longitud": "",
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 2,
    "miembrosHogarEconomicamenteResponsables": 0,
    "grupoEtnico": "Campesino",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "JAQUELINE GARZON MORENO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 52661987,
    "headFamilyPhone": 3208341436,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "JAQUELINE GARZON MORENO",
    "cedula": 52661987,
    "telefono": 3208341436,
    "email": "",
    "finca": "EL JAZMIN",
    "latitud": 4.45422,
    "longitud": -74.32641,
    "registroCatastral": "157-175",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 450000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "JONATAN VILLALOBOS GUCHUVO",
    "headFamilyGender": "Hombre",
    "headFamilyIdentification": 1069757882,
    "headFamilyPhone": 3132158265,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "JONATAN VILLALOBOS GUCHUVO",
    "cedula": 1069757882,
    "telefono": 3132158265,
    "email": "",
    "finca": "",
    "latitud": "",
    "longitud": "",
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 1,
    "miembrosHogarEconomicamenteResponsables": 1,
    "grupoEtnico": "Joven rural",
    "lugarResidencia": "",
    "afilicacionSeguridadSocial": "",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "JOSE ISRAEL ACOSTA ACOSTA",
    "headFamilyGender": "Hombre",
    "headFamilyIdentification": 11381492,
    "headFamilyPhone": 3215203869,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "JOSE ISRAEL ACOSTA ACOSTA",
    "cedula": 11381492,
    "telefono": 3215203869,
    "email": "",
    "finca": "el pedregal",
    "latitud": 4.27557,
    "longitud": -74.19463,
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 2,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Campesino",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "LEONEL MARINO GARCIA REINA",
    "headFamilyGender": "Hombre",
    "headFamilyIdentification": 11386653,
    "headFamilyPhone": 3124549403,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "LEONEL MARINO GARCIA REINA",
    "cedula": 11386653,
    "telefono": 3124549403,
    "email": "",
    "finca": "el desafio",
    "latitud": 4.27991,
    "longitud": -74.19383,
    "registroCatastral": "157-110344",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 1,
    "miembrosHogarEconomicamenteResponsables": 0,
    "grupoEtnico": "Campesino",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "LILIA SOACHA GUZMAN",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 39624924,
    "headFamilyPhone": 3142194040,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "LILIA SOACHA GUZMAN",
    "cedula": 39624924,
    "telefono": 3142194040,
    "email": "liliasoachaguzman@gmail.com",
    "finca": "LA PRIMAVERA",
    "latitud": 4.6472,
    "longitud": -74.33333,
    "registroCatastral": "157-106341",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 1,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 500000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "LUZ ADRIANA SARMIENTO ORTIZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 1072497702,
    "headFamilyPhone": 3208248212,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "LUZ ADRIANA SARMIENTO ORTIZ",
    "cedula": 1072497702,
    "telefono": 3208248212,
    "email": "luzadrianasarmientoortiz@gmail.com",
    "finca": "PARCELA 11 SAN VICENTE",
    "latitud": 4.46663,
    "longitud": -74.333,
    "registroCatastral": "157-52436",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 6,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Joven rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 800000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "LUZ DARY RODRIGUEZ DIAZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 35253942,
    "headFamilyPhone": 3227344377,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "LUZ DARY RODRIGUEZ DIAZ",
    "cedula": 35253942,
    "telefono": 3227344377,
    "email": "",
    "finca": "LOTE",
    "latitud": 4.4583,
    "longitud": -74.33268,
    "registroCatastral": "157-139970",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 3,
    "miembrosHogarEconomicamenteResponsables": 1,
    "grupoEtnico": "Madre cabeza familia",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 450000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "LUZ DARY VILLALOBOS GUCHUVO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 35252646,
    "headFamilyPhone": "313 8037661",
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "LUZ DARY VILLALOBOS GUCHUVO",
    "cedula": 35252646,
    "telefono": "313 8037661",
    "email": "luzda3.27@hotmail.com",
    "finca": "TOCAREMA",
    "latitud": 4.44029,
    "longitud": -74.32487,
    "registroCatastral": "157-22375",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 5,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 900000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "LUZ MARINA DIMATE PENAGOS",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 20823301,
    "headFamilyPhone": 3214450370,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "LUZ MARINA DIMATE PENAGOS",
    "cedula": 20823301,
    "telefono": 3214450370,
    "email": "",
    "finca": "PARCELA 17",
    "latitud": 4.45868,
    "longitud": -74.85868,
    "registroCatastral": "157-106586",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 3,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Adulto mayor",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 450000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "MARIA ARCENOBIS FORERO DÍAZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 39617226,
    "headFamilyPhone": 3219108130,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "MARIA ARCENOBIS FORERO DÍAZ",
    "cedula": 39617226,
    "telefono": 3219108130,
    "email": "",
    "finca": "EL PLACER",
    "latitud": 4.44873,
    "longitud": -74.32483,
    "registroCatastral": "157-5417",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 2,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 500000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "MARIA DILMA FORERO DIAZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 39614728,
    "headFamilyPhone": 3118933970,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "MARIA DILMA FORERO DIAZ",
    "cedula": 39614728,
    "telefono": 3118933970,
    "email": "",
    "finca": "LA ESPERANZA",
    "latitud": 4.46077,
    "longitud": -74.32253,
    "registroCatastral": "157-97688",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 2,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Adulto mayor",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 400000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "MARIA ISBELIA CARREÑO CARREÑO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 23573895,
    "headFamilyPhone": 3112144876,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "MARIA ISBELIA CARREÑO CARREÑO",
    "cedula": 23573895,
    "telefono": 3112144876,
    "email": "",
    "finca": "",
    "latitud": "",
    "longitud": "",
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 2,
    "miembrosHogarEconomicamenteResponsables": 1,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "MARIA OFELIA RODRIGUEZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 39614792,
    "headFamilyPhone": 3213628638,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "MARIA OFELIA RODRIGUEZ",
    "cedula": 39614792,
    "telefono": 3213628638,
    "email": "",
    "finca": "la primavera",
    "latitud": 4.2752,
    "longitud": -74.19296,
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 1,
    "miembrosHogarEconomicamenteResponsables": 0,
    "grupoEtnico": "Adulto mayor",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "MARIBEL BABATIVA RODRIGUEZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 39625070,
    "headFamilyPhone": 3174538641,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "MARIBEL BABATIVA RODRIGUEZ",
    "cedula": 39625070,
    "telefono": 3174538641,
    "email": "diegoalejandro.ramirez@outlook.es",
    "finca": "BUENA VISTA",
    "latitud": 4.46173,
    "longitud": -74.32013,
    "registroCatastral": "157-166",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 3,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "4. Poseedor",
    "gastosUltimoMes": 600000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "NANCY YOLIMA RODRIGUEZ GALVIS",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 35252348,
    "headFamilyPhone": 3213325333,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "NANCY YOLIMA RODRIGUEZ GALVIS",
    "cedula": 35252348,
    "telefono": 3213325333,
    "email": "ryolima725@gmail.com",
    "finca": "LAS DELICIAS LOTE 3",
    "latitud": 4.4609,
    "longitud": -74.32577,
    "registroCatastral": "157-106043",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 500000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "NIDIA MARCELA RODRIGUEZ RODRIGUEZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 35252007,
    "headFamilyPhone": 3206787980,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "NIDIA MARCELA RODRIGUEZ RODRIGUEZ",
    "cedula": 35252007,
    "telefono": 3206787980,
    "email": "",
    "finca": "CANOAS",
    "latitud": 4.45901,
    "longitud": -74.31944,
    "registroCatastral": "157-109298",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 3,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "5.Ocupante",
    "gastosUltimoMes": 500000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "NUVIA DIMATE PENAGOS",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 20823757,
    "headFamilyPhone": 3138154027,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "NUVIA DIMATE PENAGOS",
    "cedula": 20823757,
    "telefono": 3138154027,
    "email": "",
    "finca": "",
    "latitud": "",
    "longitud": "",
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 1,
    "miembrosHogarEconomicamenteResponsables": 0,
    "grupoEtnico": "Discapacitado",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "DI-D21: Población no pobre",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "2. Arrendatario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "NUVIA MARITZA SOLORZANO RODRIGUEZ",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 35250970,
    "headFamilyPhone": 3103482834,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "NUVIA MARITZA SOLORZANO RODRIGUEZ",
    "cedula": 35250970,
    "telefono": 3103482834,
    "email": "",
    "finca": "el recuerdo",
    "latitud": 4.28086,
    "longitud": -74.19138,
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 3,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "OLIVA PEÑUELA GUERRERO",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 39618033,
    "headFamilyPhone": 3045312323,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "OLIVA PEÑUELA GUERRERO",
    "cedula": 39618033,
    "telefono": 3045312323,
    "email": "",
    "finca": "LOTE # 4",
    "latitud": 4.45998,
    "longitud": -74.32442,
    "registroCatastral": "157-97691",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 1,
    "grupoEtnico": "Adulto mayor",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "C1-C18: Población vulnerable",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 300000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "RUBIELA DIAZ BERNAL",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 1072492902,
    "headFamilyPhone": 3143116337,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "RUBIELA DIAZ BERNAL",
    "cedula": 1072492902,
    "telefono": 3143116337,
    "email": "rubielabernal529@gmail.com",
    "finca": "EL ARENAL",
    "latitud": 4.46085,
    "longitud": -74.32152,
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "1. Propietario",
    "gastosUltimoMes": 950000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "VICTOR JAVIER FORERO RODRIGUEZ",
    "headFamilyGender": "Hombre",
    "headFamilyIdentification": 11259041,
    "headFamilyPhone": 3202518990,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "VICTOR JAVIER FORERO RODRIGUEZ",
    "cedula": 11259041,
    "telefono": 3202518990,
    "email": "",
    "finca": "",
    "latitud": "",
    "longitud": "",
    "registroCatastral": "",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 3,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Campesino",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "2. Arrendatario",
    "gastosUltimoMes": "",
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "YENNY ESPERANZA RAMIREZ CAÑON",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 1024496170,
    "headFamilyPhone": 3058188166,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "YENNY ESPERANZA RAMIREZ CAÑON",
    "cedula": 1024496170,
    "telefono": 3058188166,
    "email": "jedaeve2021@gmail.com",
    "finca": "LA PONDEROSA PARCELA 25",
    "latitud": 4.4681,
    "longitud": -74.32882,
    "registroCatastral": "157-22431",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 4,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "A1 -A5: Pobreza extrema",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "4. Poseedor",
    "gastosUltimoMes": 400000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  },
  {
    "headFamilyFirstName": "ZULMA MARYOLI VILLALOBOS DIMATE",
    "headFamilyGender": "Mujer",
    "headFamilyIdentification": 35254749,
    "headFamilyPhone": 3209609877,
    "headFamilyTypeId": {
      "id": 1,
      "long": "Cedula",
      "name": "CC"
    },
    "birthDate": "",
    "nombre": "ZULMA MARYOLI VILLALOBOS DIMATE",
    "cedula": 35254749,
    "telefono": 3209609877,
    "email": "zulmavillalobos09@gmail.com",
    "finca": "PARCELA 17",
    "latitud": 4.45682,
    "longitud": -74.32391,
    "registroCatastral": "157-31727",
    "municipio": "SILVANIA",
    "vereda": "AGUABONITA",
    "numeroMiembrosHogar": 5,
    "miembrosHogarEconomicamenteResponsables": 2,
    "grupoEtnico": "Mujer rural",
    "lugarResidencia": "Finca",
    "afilicacionSeguridadSocial": "SI SUBSIDIADO",
    "grupoSisben": "B1-B7: Pobreza moderada",
    "accesoTierra": "SI",
    "relacionTenenciaTierra": "4. Poseedor",
    "gastosUltimoMes": 900000,
    "perteneceOrganizacionProductiva": "SI",
    "nombreOrganizacion": "FORJADORES DE PAZ",
    "tiempoHabitandoSectorRural": "Más de 3 años"
  }
]